window.LANG = {
  en: {
    nav_home:"Home", nav_check:"Check Health", nav_upload:"Upload Report",
    nav_diet:"Diet Plan", nav_family:"Family", nav_tips:"Health Tips", nav_about:"About",
    hero_badge:"Made for India",
    hero_title_1:"Know Your", hero_title_2:"Health Risk",
    hero_sub:"Know your risk of diabetes, BP and heart disease. Enter your data and we will guide you.",
    btn_check:"Check My Health", btn_upload:"Upload Doctor Report",
    disclaimer:"This tool is for awareness only. Not a medical diagnosis. Always consult your doctor.",
    features_label:"Features", features_title:"What Will You Get?", features_sub:"Everything in one place",
    f1_title:"Risk Calculator", f1_desc:"Age, weight, BP, sugar - calculates risk score. Shows Low, Moderate or High.",
    f2_title:"Symptom Checker", f2_desc:"Headache, fever, stomach ache, chest pain - type how you feel.",
    f3_title:"Doctor Report Upload", f3_desc:"Upload doctor prescription - we will read data and assess risk.",
    f4_title:"Indian Hospitals", f4_desc:"Mumbai, Delhi, Bangalore - top hospitals with phone and map links.",
    f5_title:"Medicine Info", f5_desc:"Crocin, Dolo, Metformin - type Indian medicine names, get FDA info.",
    f6_title:"Disease Tracker", f6_desc:"See India and global disease statistics in real time.",
    f7_title:"7-Day Diet Plan", f7_desc:"Personalized Indian meal plans for diabetes, BP, low B12, weight loss and more.",
    f8_title:"Family Health Tracker", f8_desc:"Add your parents and siblings. See combined family risk and share on WhatsApp.",
    cta:"Start Now - It is Free!",
    steps_label:"How It Works", steps_title:"Simple 4 Steps",
    step1_title:"Step 1 - Enter Data", step1_desc:"Enter your age, height, weight, BP, blood sugar and lifestyle.",
    step2_title:"Step 2 - AI Analysis", step2_desc:"Our engine calculates risk score combining 7 factors from 0 to 100 percent.",
    step3_title:"Step 3 - See Results", step3_desc:"Get risk level, BMI, chart and personalized recommendations.",
    step4_title:"Step 4 - See Doctor", step4_desc:"Go to your doctor with results for proper advice.",
    footer_made:"Made by Sagar",
    loading_text:"Analyzing your health data...", loading_sub:"Please wait, results are coming",
    form_label:"Step 1", form_title:"Enter Your Data", form_sub:"Accurate data gives accurate results.",
    toggle_label:"What Do You Want to Check?", basic_title:"Basic Information",
    age_label:"Age (years)", gender_label:"Gender", height_label:"Height (cm)", weight_label:"Weight (kg)",
    bp_label:"Blood Pressure Systolic (mmHg)", glucose_label:"Blood Sugar Fasting (mg/dL)",
    bp_hint:"Upper number on BP machine", glucose_hint:"Blood test without eating. Normal: 70-99",
    gender_select:"Select", gender_male:"Male", gender_female:"Female", gender_other:"Prefer not to say",
    lifestyle_title:"Lifestyle", family_label:"Family History of Diabetes or BP?",
    family_no:"No", family_yes:"Yes", smoking_label:"Smoking", smoking_no:"Non Smoker", smoking_yes:"Smoker",
    activity_label:"Physical Activity Level",
    act_sedentary:"None (Sedentary)", act_light:"Light", act_moderate:"Moderate", act_active:"Very Active",
    symptom_title:"Symptoms (Optional)", symptom_label:"What Problem Are You Having?",
    symptom_placeholder:"Write like: headache, fever, chest pain, stomach ache, dizziness...",
    symptom_hint:"Write in Hindi or English - both are understood",
    medicine_title:"Medicine Name (Optional)", medicine_label:"Are You Taking Any Medicine?",
    medicine_placeholder:"Like: Crocin, Dolo 650, Metformin, Combiflam, Pan 40, Telma...",
    medicine_hint:"Indian brand names work too",
    hospital_title:"Nearby Hospitals (Optional)", city_label:"Enter Your City",
    city_placeholder:"Like: Mumbai, Delhi, Bangalore, Hyderabad, Chennai, Pune",
    city_hint:"Top hospitals in major Indian cities will be shown",
    specialty_label:"What Kind of Doctor Do You Need?",
    spec_general:"General / Family Doctor", spec_cardiology:"Heart Doctor (Cardiologist)",
    spec_endo:"Diabetes Doctor", spec_internal:"General Medicine",
    spec_nutrition:"Diet Expert (Dietitian)", spec_psychiatry:"Mental Health Doctor",
    submit_btn:"Check My Health Risk",
    form_error:"Please fill required fields - Age, Height, Weight, BP and Blood Sugar.",
    results_label:"Your Results", results_title:"Your Health Report", risk_label:"Overall Risk Level",
    risk_low:"Low Risk - All Good", risk_moderate:"Moderate Risk - Pay Attention", risk_high:"High Risk - See Doctor Immediately",
    gauge_low:"Low (0-30%)", gauge_mod:"Moderate (31-60%)", gauge_high:"High (61%+)",
    bmi_label:"Body Mass Index (BMI)",
    chart_title:"Risk Factor Breakdown", nutrition_title:"Nutrition Data", drug_title:"Medicine Information",
    rec_title:"Suggestions For You",
    notice:"This assessment uses a weighted scoring model. It is for awareness only. Consult a certified doctor.",
    reassess:"Check Again", maps_link:"Open in Google Maps",
    toggle_hi:"Hindi", toggle_en:"English", theme_light:"Light Mode", theme_dark:"Dark Mode",
    nutrition_title:"Nutrition Data"
  },
  hi: {
    nav_home:"होम", nav_check:"स्वास्थ्य जांच", nav_upload:"रिपोर्ट अपलोड",
    nav_diet:"डाइट प्लान", nav_family:"परिवार", nav_tips:"स्वास्थ्य सुझाव", nav_about:"जानकारी",
    hero_badge:"भारत के लिए बनाया गया",
    hero_title_1:"अपना", hero_title_2:"स्वास्थ्य जोखिम जानो",
    hero_sub:"मधुमेह, रक्तचाप और हृदय रोग का खतरा पहले से जानो। अपना डेटा डालो, हम मार्गदर्शन करेंगे।",
    btn_check:"अपना स्वास्थ्य जांचो", btn_upload:"डॉक्टर की रिपोर्ट अपलोड करो",
    disclaimer:"यह उपकरण केवल जागरूकता के लिए है। यह कोई चिकित्सा निदान नहीं है। हमेशा अपने डॉक्टर से मिलें।",
    features_label:"सुविधाएं", features_title:"क्या क्या मिलेगा?", features_sub:"एक जगह सब कुछ",
    f1_title:"जोखिम कैलकुलेटर", f1_desc:"उम्र, वजन, रक्तचाप, शर्करा - सभी कारकों से जोखिम स्कोर।",
    f2_title:"लक्षण जांचकर्ता", f2_desc:"सिर दर्द, बुखार, पेट दर्द - जैसा महसूस हो वैसे लिखो।",
    f3_title:"डॉक्टर रिपोर्ट अपलोड", f3_desc:"डॉक्टर की पर्ची अपलोड करो - हम डेटा पढ़कर जोखिम का आकलन करेंगे।",
    f4_title:"भारतीय अस्पताल", f4_desc:"मुंबई, दिल्ली, बेंगलुरु - शीर्ष अस्पताल फोन और नक्शे के साथ।",
    f5_title:"दवाई की जानकारी", f5_desc:"क्रोसिन, डोलो, मेटफॉर्मिन - भारतीय दवाई के नाम टाइप करो।",
    f6_title:"रोग ट्रैकर", f6_desc:"भारत और वैश्विक रोग आंकड़े वास्तविक समय में देखो।",
    f7_title:"7-दिन डाइट प्लान", f7_desc:"मधुमेह, BP, कम B12, वजन घटाने के लिए भारतीय भोजन योजना।",
    f8_title:"पारिवारिक स्वास्थ्य ट्रैकर", f8_desc:"माता-पिता और भाई-बहन जोड़ो। मिलाकर जोखिम देखो और WhatsApp पर शेयर करो।",
    cta:"अभी शुरू करो - बिल्कुल मुफ्त!",
    steps_label:"यह कैसे काम करता है", steps_title:"सरल 4 चरण",
    step1_title:"चरण 1 - डेटा डालो", step1_desc:"अपनी उम्र, ऊंचाई, वजन, रक्तचाप, रक्त शर्करा डालो।",
    step2_title:"चरण 2 - एआई विश्लेषण", step2_desc:"हमारा इंजन 7 कारकों को मिलाकर जोखिम स्कोर की गणना करता है।",
    step3_title:"चरण 3 - परिणाम देखो", step3_desc:"जोखिम स्तर, बीएमआई, चार्ट और सिफारिशें मिलती हैं।",
    step4_title:"चरण 4 - डॉक्टर से मिलो", step4_desc:"परिणाम लेकर अपने डॉक्टर के पास जाओ।",
    footer_made:"सागर द्वारा बनाया गया",
    loading_text:"आपका स्वास्थ्य डेटा विश्लेषण हो रहा है...", loading_sub:"थोड़ा इंतजार करो, परिणाम आ रहे हैं",
    form_label:"चरण 1", form_title:"अपना डेटा डालो", form_sub:"सही डेटा देने से सही परिणाम मिलेगा।",
    toggle_label:"क्या क्या जांचना है?", basic_title:"बुनियादी जानकारी",
    age_label:"उम्र (वर्ष)", gender_label:"लिंग", height_label:"ऊंचाई (सेमी)", weight_label:"वजन (किग्रा)",
    bp_label:"रक्तचाप सिस्टोलिक (mmHg)", glucose_label:"रक्त शर्करा उपवास (mg/dL)",
    bp_hint:"रक्तचाप मशीन में ऊपर वाला नंबर", glucose_hint:"खाना खाए बिना रक्त परीक्षण। सामान्य: 70-99",
    gender_select:"चुनो", gender_male:"पुरुष", gender_female:"महिला", gender_other:"नहीं बताना",
    lifestyle_title:"जीवनशैली", family_label:"परिवार में मधुमेह या रक्तचाप है?",
    family_no:"नहीं", family_yes:"हां", smoking_label:"धूम्रपान", smoking_no:"नहीं पीता", smoking_yes:"पीता हूं",
    activity_label:"शारीरिक गतिविधि का स्तर",
    act_sedentary:"बिल्कुल नहीं (गतिहीन)", act_light:"थोड़ी (हल्की)", act_moderate:"ठीक-ठाक (मध्यम)", act_active:"बहुत ज्यादा (सक्रिय)",
    symptom_title:"लक्षण (वैकल्पिक)", symptom_label:"क्या तकलीफ हो रही है?",
    symptom_placeholder:"ऐसे लिखो: सिर दर्द, बुखार, सीने में दर्द, पेट दर्द...",
    symptom_hint:"हिंदी या अंग्रेजी में लिखो - दोनों समझ में आता है",
    medicine_title:"दवाई का नाम (वैकल्पिक)", medicine_label:"कोई दवाई ले रहे हो?",
    medicine_placeholder:"जैसे: क्रोसिन, डोलो 650, मेटफॉर्मिन, कॉम्बीफ्लाम...",
    medicine_hint:"भारतीय ब्रांड नाम भी चलेगा",
    hospital_title:"नजदीकी अस्पताल (वैकल्पिक)", city_label:"अपना शहर लिखो",
    city_placeholder:"जैसे: Mumbai, Delhi, Bangalore, Hyderabad",
    city_hint:"प्रमुख भारतीय शहरों के शीर्ष अस्पताल दिखाई देंगे",
    specialty_label:"किस डॉक्टर की जरूरत है?",
    spec_general:"सामान्य / पारिवारिक डॉक्टर", spec_cardiology:"हृदय रोग विशेषज्ञ",
    spec_endo:"मधुमेह डॉक्टर", spec_internal:"सामान्य चिकित्सा",
    spec_nutrition:"आहार विशेषज्ञ", spec_psychiatry:"मानसिक स्वास्थ्य डॉक्टर",
    submit_btn:"मेरा स्वास्थ्य जोखिम बताओ",
    form_error:"जरूरी फील्ड भरो - उम्र, ऊंचाई, वजन, रक्तचाप और रक्त शर्करा।",
    results_label:"आपके परिणाम", results_title:"आपकी स्वास्थ्य रिपोर्ट", risk_label:"कुल जोखिम स्तर",
    risk_low:"कम जोखिम - ठीक है", risk_moderate:"मध्यम जोखिम - ध्यान दो", risk_high:"अधिक जोखिम - तुरंत डॉक्टर से मिलो",
    gauge_low:"कम (0-30%)", gauge_mod:"मध्यम (31-60%)", gauge_high:"अधिक (61%+)",
    bmi_label:"बॉडी मास इंडेक्स (बीएमआई)",
    chart_title:"जोखिम कारक विवरण", nutrition_title:"पोषण डेटा", drug_title:"दवाई की जानकारी",
    rec_title:"आपके लिए सुझाव",
    notice:"यह आकलन केवल जागरूकता के लिए है। कोई नैदानिक निदान नहीं है। प्रमाणित डॉक्टर से मिलें।",
    reassess:"दोबारा जांचो", maps_link:"गूगल मैप्स में खोलो",
    toggle_hi:"हिंदी", toggle_en:"English", theme_light:"लाइट मोड", theme_dark:"डार्क मोड"
  }
};